# No automatic build triggering. bump build
trigger:
- master

pool:
  vmImage: 'vs2017-win2016'
strategy:
  matrix:
    Python36:
      python.version: '3.6'

variables: 
  artifact_dir: $(Build.ArtifactStagingDirectory)\build

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    echo $(Build.ArtifactStagingDirectory)
    dir /s
  displayName: 'debug'

#- script: |
#    python -m pip install --upgrade pip
#    pip install conan
#  displayName: 'Install build dependencies'

- task: BatchScript@1
  inputs:
    filename: 'build.cmd'
    arguments: Build.ArtifactStagingDirectory $(Build.ArtifactStagingDirectory) Build.SourcesDirectory $(Build.SourcesDirectory)
  displayName: 'build'
  
- script: |
    echo %cd%
    dir
    test_exe.cmd -r junit -o test_exe.xml
  workingDirectory: build\bin
  displayName: 'run test exe'

- script: |
    copy .\build\_CPack_Packages\win64\ZIP\*.zip $(Build.ArtifactStagingDirectory)\build
  displayName: "Copy build artifact to Artifact Staging Directory."

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '*.xml'
    searchFolder: $(Build.SourcesDirectory)/build/bin

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: build\_CPack_Packages\win64\ZIP
    ArtifactName: 'CPack'
    publishLocation: 'Container'

- task: UniversalPackages@0
  inputs:
    command: 'publish'
    publishDirectory: $(artifact_dir)
    feedsToUsePublish: 'internal'
    vstsFeedPublish: 'recruitment-test'
    vstsFeedPackagePublish: 'example_package'
    versionOption: 'patch'
